name: chatbot_mini
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch-cpu
  - sentence-transformers
  - pip:
      - requests
      - beautifulsoup4
      - python-dotenv
      - chromadb
      - openai
      - langchain
      - langchain-community
      - langchain-text-splitters
      - pypdf
      - python-docx
      - unstructured
      - networkx
      - streamlit
      - fastapi
      - uvicorn