name: chatbot_mini
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - libstdcxx-ng
  - libgcc-ng
  - numpy
  - pandas
  - scipy
  - matplotlib-base
  - pyyaml
  - typing-extensions
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - dataclasses-json==0.6.7
      - distlib==0.4.0
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - identify==2.6.15
      - idna==3.10
      - jinja2==3.1.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-community==0.3.30
      - langchain-core==0.3.78
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.32
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.3
      - nodeenv==1.9.1
      - orjson==3.11.3
      - platformdirs==4.5.0
      - pre-commit==4.3.0
      - propcache==0.3.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - PyPDF2==3.0.1
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - reportlab==4.4.4
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - sympy==1.13.1
      - tenacity==9.1.2
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - virtualenv==20.35.3
      - yarl==1.20.1
      - zstandard==0.25.0
